### ISSUE TITLE
Complete Application option for worker does not do anything

### ISSUE THREAD

**Issue by danielsjoo** [keepid/keepid_client#400]
When a worker clicks the three dots for a client and selects "complete application", nothing happens

<img width="879" alt="Screen Shot 2022-07-13 at 2 14 51 AM" src="https://user-images.githubusercontent.com/68679808/178697884-20d4febe-0790-43b9-9e50-bcb340694512.png">
.

**Comment by crchong1** [comment]
Fixed by worker actions for clients

**Comment by mkhagan8** [comment]
Still not working, here's a video:

https://user-images.githubusercontent.com/109312540/179079117-bf0c9854-1208-4944-a59b-182536ac3560.mp4
