### ISSUE TITLE
LOGGED IN AS ADMIN - Astronauts Appear when try to view uploaded document from Admin Page

### ISSUE THREAD

**Issue by JohnBaek-wr** [keepid/keepid_client#56]
![image](https://user-images.githubusercontent.com/65623389/94736734-b5527a80-033a-11eb-8269-5cc1456660c9.png)

I've taken quite a liking to young Martin's imitation. I've already uploaded _A Storm of Swords_ (or so I think, because I cannot locate it) and want to upload _A Game of Thrones_. To see a preview to see if I have the correct document, I hit View, and these funny men appear. Not Andals, nor descendants of the Númenóreans.

**Comment by crchong1** [comment]
i am looking into this

**Comment by crchong1** [comment]
fixed

**Comment by JohnBaek-wr** [comment]
![image](https://user-images.githubusercontent.com/65623389/94751920-c958a500-0357-11eb-849f-131867140bda.png)

Still not working - could it my computer/browser/something?
